apiVersion: apps/v1
kind: Deployment
metadata:
  name: em-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: em-backend
  template:
    metadata:
      name: backend
      labels:
        app: em-backend
    spec:
      containers:
        - name: em-backend
          image: destroyerxx/em-springboot-backend:1.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/employee_db?useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            
            